### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kingtak66** [ghodsizadeh/tehran-stocks#34]
# وقتی میخوام دیتا بیس روبسازم این ارور رو میده.چنید بار دیتا بیس رو حذف کردم و دوباره دستور رو زدم.یا ناقص دانلود میکنه یا این پیغامو میده

PS C:\Users\MyName\Desktop\tehran-stocks-master\dist> ts-get init
No database founded.
creating database
DataBase created in: C:\Users\MyName\tse
downloding  stock name and details from tccim
may take few minutes
Downloading group ids...
Traceback (most recent call last):7% completed
  File "C:\Program Files\Python\Python38\Scripts\ts-get", line 6, in <module>
    import tehran_stocks as ts
  File "C:\Program Files\Python\Python38\lib\site-packages\tehran_stocks\__init__.py", line 19, in <module>
    fill_db()
  File "C:\Program Files\Python\Python38\lib\site-packages\tehran_stocks\initializer.py", line 21, in fill_db
    fill_stock_table()
  File "C:\Program Files\Python\Python38\lib\site-packages\tehran_stocks\download\names.py", line 104, in fill_stock_table
    _ = [get_stock_detail(s, int(group)) for s in stocks]
  File "C:\Program Files\Python\Python38\lib\site-packages\tehran_stocks\download\names.py", line 104, in <listcomp>
    _ = [get_stock_detail(s, int(group)) for s in stocks]
  File "C:\Program Files\Python\Python38\lib\site-packages\tehran_stocks\download\names.py", line 47, in get_stock_detail
    stock["instId"] = re.findall(r"InstrumentID='([\w\d]*)',", r.text)[0]
IndexError: list index out of range

**Comment by ghodsizadeh** [comment]
این یک خطای مدیریت نشده است که برخی اوقات به علت مشکلات ارتباطی  بوجود میاد اگر مجدد اقدام کنید  احتمالا مشکل حل میشه و سعی می‌کنم در نسخه‌های بعدی هم این مشکل رو رفع کنم.

**Comment by artadp** [comment]
من به این مشکل برخورد کردم و مجبور شدم هر بار دیتابیس رو پاک کنم. خواهشمندم این مسئله رو حل کنید. سپاس

**Comment by ghodsizadeh** [comment]
این مسئله توی نسخه جدید حل شده.
