### ISSUE TITLE
مشکل در دانلود اطلاعات

### ISSUE THREAD

**Issue by eenvid** [ghodsizadeh/tehran-stocks#4]
سلام
من با دستور زیر دیتابیس رو درست میکنم و 100 میشه
import tehran_stocks
بعد که 100% تموم میشه و ازم سوال میپرسه و بله رو وارد میکنم با ارور زیر مواجه میشم

downloading group: 98, changes: 100.0% completed

```python
Add all groups, you can download stock price by following codes
from tehran_stocks import downloader
 downloader.download_all() # for downloading all data
downloader.download_group(group_id) # to download specefic group data
downloader.download_stock(stock) to downloand stock specefic
Stock table is available now, example:
from tehran_stocks import Stocks
stock =Stock.query.filter_by(name="کگل").first()
Do you want to download all price? [y,(n)]y
Downloading price:
progress {100*int((i+1)/len(codes):.2f)}
Traceback (most recent call last):
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Envid\Desktop\sad.py", line 1, in <module>
    import tehran_stocks
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\tehran_stocks\__init__.py", line 19, in <module>
    fill_db()
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\tehran_stocks\initializer.py", line 28, in fill_db
    get_all_price()
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\tehran_stocks\download\price.py", line 62, in get_all_price
    update_group(code)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\tehran_stocks\download\price.py", line 49, in update_group
    stocks = db.session.query(Stocks.code).filter_by(group_code=code).all()
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 3174, in all
    return list(self)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 3330, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 3355, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Envid\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT stocks.code AS stocks_code 
FROM stocks 
WHERE stocks.group_code = ?]
[parameters: ((10,))]
(Background on this error at: http://sqlalche.me/e/rvf5)‍‍```

**Comment by ghodsizadeh** [comment]
سلام میشه بگید نسخه پایتونتون چنده؟

**Comment by eenvid** [comment]
python 3.7 64bit

**Comment by majid682008** [comment]
سلام
من هم دقیقا همین مشکل رو دارم. من با virtualenv 
نصبش کردم ولی باز مشکل دارم همین ایراد دیتابیس را می دهد.

**Comment by gr8linux** [comment]
I fix the issue in my own fork
https://github.com/gr8linux/tehran-stocks
