### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'df'

### ISSUE THREAD

**Issue by arashhp78** [ghodsizadeh/tehran-stocks#52]
با سلام
دیتا فریم df اصلا قابل استفاده نمیباشد

`from tehran_stocks import Stocks

stock = Stocks.query.filter_by(name='کگل').first()

print(stock.df)
`

Traceback (most recent call last):
  File "C:/Users/KING ARASH/PycharmProjects/aa/trial6.py", line 9, in <module>
    print(stock.df)
AttributeError: 'NoneType' object has no attribute 'df'

**Comment by saeedmie85** [comment]
من هم با همچین مشکلی روبرو هستم

**Comment by farhadmpr** [comment]
شما از "ك" عربی در نام "کگل" استفاده کرده اید باید از "ک" فارسی استفاده کنید

**Comment by arashhp78** [comment]
> شما از "ك" عربی در نام "کگل" استفاده کرده اید باید از "ک" فارسی استفاده کنید

خیلی ممنون
کگل را دستی تایپ میکنم
در مورد نام های دیگد مثل وتوصا و میهن هم همین مشکل هست
اگه راهنمایی کنین ممنون میشم

**Comment by arashhp78** [comment]
> شما از "ك" عربی در نام "کگل" استفاده کرده اید باید از "ک" فارسی استفاده کنید

@farhadmpr 
خیلی ممنون
کگل را دستی تایپ میکنم
در مورد نام های دیگد مثل وتوصا و میهن هم همین مشکل هست
اگه راهنمایی کنین ممنون میشم

**Comment by farhadmpr** [comment]
> > شما از "ك" عربی در نام "کگل" استفاده کرده اید باید از "ک" فارسی استفاده کنید
> 
> @farhadmpr
> خیلی ممنون
> کگل را دستی تایپ میکنم
> در مورد نام های دیگد مثل وتوصا و میهن هم همین مشکل هست
> اگه راهنمایی کنین ممنون میشم

احتمالا اطلاعات دریافتی از بورس ناقص می باشد و کامل دریافت و در دیتابیس ذخیره نشده است
فایل stocks.db را پیدا و حذف کنید و فرایند را دوباره تکرار کنید و منتظر بمانید تا دیتابیس کاملا پر شود

**Comment by arashhp78** [comment]
> > > شما از "ك" عربی در نام "کگل" استفاده کرده اید باید از "ک" فارسی استفاده کنید
> > 
> > 
> > @farhadmpr
> > خیلی ممنون
> > کگل را دستی تایپ میکنم
> > در مورد نام های دیگد مثل وتوصا و میهن هم همین مشکل هست
> > اگه راهنمایی کنین ممنون میشم
> 
> احتمالا اطلاعات دریافتی از بورس ناقص مانده و کامل در دیتابیس ذخیره نشده است
> فایل stocks.db را پیدا و حذف کنید و فرایند را دوباره تکرار کنید و منتظر بمانید تا دیتابیس کاملا پر شود

@farhadmpr . 
امکانش هست که کد آماده برای ساختن دیتا فریم چند روز اخیر برای همین بورس کگل رو بدین؟ 
چند بار امتحان کردم ولی هنوز همون مشکل رو داره

**Comment by arashhp78** [comment]
> > > شما از "ك" عربی در نام "کگل" استفاده کرده اید باید از "ک" فارسی استفاده کنید
> > 
> > 
> > @farhadmpr
> > خیلی ممنون
> > کگل را دستی تایپ میکنم
> > در مورد نام های دیگد مثل وتوصا و میهن هم همین مشکل هست
> > اگه راهنمایی کنین ممنون میشم
> 
> احتمالا اطلاعات دریافتی از بورس ناقص مانده و کامل در دیتابیس ذخیره نشده است
> فایل stocks.db را پیدا و حذف کنید و فرایند را دوباره تکرار کنید و منتظر بمانید تا دیتابیس کاملا پر شود

@farhadmpr 


با پاک کردن stocks.db : 



```
from tehran_stocks import Stocks
stock = Stocks.query.filter_by(name='کگل').first()
print(stock.df)
```


> No database founded.
> creating database
> DataBase created in: C:\Users\KING ARASH\tse
> downloding  stock name and details from tccim
> may take few minutes 
> Downloading group ids...
> Traceback (most recent call last):
>   File "C:/Users/KING ARASH/PycharmProjects/aa/test.py", line 1, in <module>
>     from tehran_stocks import Stocks
>   File "C:\Users\KING ARASH\AppData\Roaming\Python\Python37\site-packages\tehran_stocks\__init__.py", line 19, in <module>
>     fill_db()
>   File "C:\Users\KING ARASH\AppData\Roaming\Python\Python37\site-packages\tehran_stocks\initializer.py", line 21, in fill_db
>     fill_stock_table()
>   File "C:\Users\KING ARASH\AppData\Roaming\Python\Python37\site-packages\tehran_stocks\download\names.py", line 104, in fill_stock_table
>     _ = [get_stock_detail(s, int(group)) for s in stocks]
>   File "C:\Users\KING ARASH\AppData\Roaming\Python\Python37\site-packages\tehran_stocks\download\names.py", line 104, in <listcomp>
>     _ = [get_stock_detail(s, int(group)) for s in stocks]
>   File "C:\Users\KING ARASH\AppData\Roaming\Python\Python37\site-packages\tehran_stocks\download\names.py", line 47, in get_stock_detail
>     stock["instId"] = re.findall(r"InstrumentID='([\w\d]*)|$',", r.text)[0]
> IndexError: list index out of range






که با دوباره ران کردن کد : 

> Traceback (most recent call last):
>   File "C:/Users/KING ARASH/PycharmProjects/aa/test.py", line 3, in <module>
>     print(stock.df)
> AttributeError: 'NoneType' object has no attribute 'df'





امکانش هست که کد آماده برای ساختن دیتا فریم چند روز اخیر برای همین بورس کگل رو بدین؟
چند بار امتحان کردم ولی هنوز همون مشکل رو داره

**Comment by bestheroforever** [comment]
دریافت دیتای historical برای هر سهم امکان پذیر نیست؟

**Comment by arashhp78** [comment]
> دریافت دیتای historical برای هر سهم امکان پذیر نیست؟

@bestheroforever 
خیر ارور میده هنوز 
امکانش هست کد مورد نیاز که شما هم استفاده می‌کنید رو اینجا قرار بدین؟

**Comment by abolfalk** [comment]
من هم با همین مشکل رو برو هستم برای بعضی سهم ها مثل زمگسا و سیمرغ حتی وقتی کد اونها رو هم وارد میکنم با این مشکل روبرو میشم
